### ISSUE TITLE
Already have fits index files

### ISSUE THREAD

**Issue by rankinstudio** [Jusas/astrometry-api-lite#2]
I already had the fits index files I need from ansvr. I didn't select to install any. Where do I place these fits files for Astrometry-api-lite to work?

I see this in the docs: <installation directory>/indexes.

So I'm assuming mine would be C:\astrometry-api-lite\indexes?

Thanks!

**Comment by Jusas** [comment]
Yes and no;

By default the installer will download them to <your install dir>/indexes. However if you do not download them the installer will not configure the download path to astrometry.net either (because it assumes you have it all set up by yourself already) - which means that in order to use your pre-downloaded indexes you'll need to edit the configuration manually.

Astrometry.net configuration is installed by default to /etc/astrometry.cfg in the Windows Subsystem for Linux (Ubuntu). That's the file you'll need to edit and add the path there. The path is a Linux path, so if your Windows indexes dir is C:\astrometry-api-lite\indexes, then the path to use is /mnt/c/astrometry-api-lite/indexes.

You can do this with one command: 
```echo "/mnt/c/astrometry-api-lite/indexes" | sudo tee -a /etc/astrometry.cfg > /dev/null```
